In [2]:
import torch
import numpy as np
import time
import torch.nn as nn
from torch.nn import functional as F
import warnings
device ='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [20]:
randint=torch.randint(-100,100,(6,))
randint

tensor([-50, -42, -85, -74,  52, -39])

In [21]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [22]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
input= torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [26]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [27]:
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [28]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [29]:
a = torch.empty((2,3), dtype=torch.int64)
emptylike=torch.empty_like(a)
emptylike

tensor([[5223573626992,             0,             0],
        [            0,             0,             0]])

In [39]:
%%time
start_time =time.time()
zeros= torch.zeros(1,1)
end_time=time.time()

elapsed_time=end_time-start_time
print(f"{elapsed_time:8f}")

0.000000
CPU times: total: 0 ns
Wall time: 0 ns


In [38]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time-start_time
print(f"{elapsed_time: 8f}")

start_time = time.time()
rand = np.multiply(np_rand1,np_rand2)
end_time=time.time()
elapsed_time= end_time-start_time
print(f"{elapsed_time: 8f}")
warnings.filterwarnings("ignore", category=DeprecationWarning)


 0.369710
 0.337298


In [41]:
# torch.stack,torch.multinomial,torch.tril,torch.triu,input.T/input.transpose,nn.linear,torch.cat,F.softmax

# Define a probability tensor
probabilities = torch.tensor([0.1,0.9])
samples =torch.multinomial(probabilities,num_samples=10,replacement= True)
print(samples)

tensor([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])


In [42]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [43]:
out=torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [44]:
out=torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [45]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float("-inf"))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [46]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [47]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [48]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
tensor3=torch.tensor([7,8,9])

stacked_tensor=torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
import torch.nn as nn
sample  = torch.tensor([10.,10.,10.])
linear= nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([-3.7900,  1.6472, -5.0215], grad_fn=<SqueezeBackward4>)


In [53]:
import torch.nn.functional as F

tensor1= torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [54]:
vocab_size= 1000
embedding_dim=100
embedding = nn.Embedding(vocab_size,embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])
embedding_out= embedding(input_indices)

print(embedding_out.shape)

torch.Size([4, 100])


In [4]:
a= torch.tensor([[1,2],[3,4],[5,6]])
b= torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [3]:
int_64 = torch.randint(1, (3, 2)).float()
float_32 = torch.rand(2,3)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [5]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[0.1200, 0.8272, 0.7622, 0.8691, 0.1592, 0.0051, 0.7025, 0.8143, 0.6094,
         0.3010],
        [0.7192, 0.0233, 0.3392, 0.6508, 0.3798, 0.7037, 0.7549, 0.9848, 0.8924,
         0.7870],
        [0.8475, 0.0211, 0.2356, 0.5625, 0.3741, 0.1686, 0.0547, 0.0372, 0.4245,
         0.2936],
        [0.6575, 0.8881, 0.0200, 0.5095, 0.9948, 0.0324, 0.0153, 0.7182, 0.5935,
         0.9768],
        [0.7732, 0.0688, 0.2934, 0.5798, 0.3619, 0.8243, 0.7520, 0.1020, 0.7366,
         0.4150],
        [0.6477, 0.7598, 0.9311, 0.6106, 0.4686, 0.0201, 0.2872, 0.0255, 0.4611,
         0.1918],
        [0.6072, 0.4813, 0.8786, 0.3196, 0.7322, 0.5540, 0.0626, 0.5006, 0.5613,
         0.2101],
        [0.9957, 0.9579, 0.3841, 0.4274, 0.9307, 0.9436, 0.6135, 0.0336, 0.3129,
         0.5776],
        [0.4292, 0.1114, 0.4922, 0.4791, 0.0240, 0.6636, 0.1915, 0.8224, 0.0352,
         0.0689],
        [0.1969, 0.8420, 0.8430, 0.4063, 0.7907, 0.8620, 0.0702, 0.7083, 0.5824,
         0.4125],
        [0

IndexError: too many indices for tensor of dimension 2

In [6]:
x = torch.tensor([-0.05],dtype=torch.float32)
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [7]:
x = torch.tensor([10],dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
